Update Jenkinsfile

diff --git a/jenkins-ci-cd-project3/Jenkinsfile b/jenkins-ci-cd-project3/Jenkinsfile
--- a/jenkins-ci-cd-project3/Jenkinsfile
+++ b/jenkins-ci-cd-project3/Jenkinsfile
@@ -10,15 +10,20 @@ pipeline {
     }
 
     stages {
-        stage('Clone') {
+        stage('Checkout SCM') {
             steps {
-                git 'https://github.com/devkelzs/jenkins-projects.git'
+                checkout scm
             }
         }
 
         stage('Build Image') {
             steps {
-                sh 'docker build -t $DOCKER_IMAGE .'
+                dir('jenkins-ci-cd-project3') {
+                    sh '''
+                        docker buildx create --use
+                        docker buildx build -t $DOCKER_IMAGE .
+                    '''
+                }
             }
         }
 
@@ -33,13 +38,27 @@ pipeline {
             }
         }
 
+        stage('Debug Workspace') {
+            steps {
+                dir('jenkins-ci-cd-project3') {
+                    sh 'ls -l'
+                }
+            }
+        }
+
         stage('Deploy to K8s') {
             steps {
                 withCredentials([file(credentialsId: 'kubeconfig-minikube', variable: 'KUBECONFIG')]) {
-                    sh '''
-                        kubectl --kubeconfig=$KUBECONFIG delete deployment nodejs-deployment --ignore-not-found=true
-                        kubectl --kubeconfig=$KUBECONFIG apply -f deployment.yaml
-                    '''
+                    dir('jenkins-ci-cd-project3') {
+                        sh '''
+                            if [ ! -f deployment.yaml ]; then
+                                echo "ERROR: deployment.yaml not found"
+                                exit 1
+                            fi
+                            kubectl --kubeconfig=$KUBECONFIG delete deployment nodejs-deployment --namespace=default --ignore-not-found=true
+                            kubectl --kubeconfig=$KUBECONFIG apply -f deployment.yaml
+                        '''
+                    }
                 }
             }
         }
